steps:
- name: "gcr.io/cloud-builders/docker"
  id: Building Docker image
  args: ["build", "-t", "gcr.io/$PROJECT_ID/purchase-predict-api:$SHORT_SHA", "."]
- name: "gcr.io/cloud-builders/docker"
  id: Pushong Docker image
  args: ["push", "gcr.io/$PROJECT_ID/purchase-predict-api:$SHORT_SHA"] 
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  id: Rendering templated K8s
  entrypoint: gcloud
  args: ["run", "deploy", "purchase-predict-api", "--image", "gcr.io/$PROJECT_ID/purchase-predict-api:$SHORT_SHA", "--region", "europe-west1", "--platform", "managed"]
images:
- gcr.io/$PROJECT_ID/purchase-predict-api:$SHORT_SHA