apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase-predict
  labels:
    app: purchase-predict
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-purchase-predict
  template:
    metadata:
      labels:
        app: pod-purchase-predict
    spec:
      containers:
      - name: pod-purchase-predict
        image: gcr.io/blent-mleng/purchase-predict-api:DOCKER_TAG
        env:
        - name: PORT 
          value: "80"
        - name: ENV 
          value: "production"
        - name: MLFLOW_SERVER
          value: "http://34.140.98.72"
        - name: MLFLOW_REGISTRY_NAME
          value: "purchase_predict"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "0.5G"
            cpu: "0.5"
          limits:
            memory: "1G"
            cpu: "1"
